[workspace]
authors = ["Hadrien Mary <hadrien.mary@gmail.com>"]
channels = ["conda-forge"]
name = "moku"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<4"
jupyterlab = ">=4.5.6,<5"
httpx = "*"
ruff = "*"
pytorch = ">=2.9.1"
ipywidgets = "*"
tqdm = "*"
ipykernel = ">=7.2.0,<8"
platformdirs = "*"
onnxruntime = ">=1.22.2"
pandas = "*"
typer = "*"
huggingface_hub = ">=1.5.0"
datasets = ">=4.6.0"
transformers = ">=5.2.0"
matplotlib = ">=3.10.8"
pillow = "*"
scikit-learn = ">=1.8.0,<2"
numpy = ">=2.4.2,<3"
torchvision = ">=0.25.0,<0.26"
torchmetrics = ">=1.8.2,<2"
accelerate = ">=1.12.0,<2"
wandb = ">=0.19.0"
gradio = ">=6.3.0"
pycocotools = ">=2.0.11,<3"
onnxscript = ">=0.5.6"
pip = ">=26.0.1,<27"
albumentations = ">=1.4.20,<3"
google-genai = ">=1.68.0,<2"

[pypi-dependencies]
moku = { path = ".", editable = true }
faster-coco-eval = ">=1.7.2, <2"
