[workspace]
authors = ["Hadrien Mary <hadrien.mary@gmail.com>"]
channels = ["conda-forge"]
name = "moku"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13,<4"
jupyterlab = "*"
httpx = "*"
ruff = "*"
pytorch = ">=2.9.1"
ipywidgets = "*"
tqdm = "*"
ipykernel = "*"
platformdirs = "*"
onnxruntime = ">=1.22.2"
pandas = ">=3.0.1"
typer = "*"
huggingface_hub = ">=1.5.0"
datasets = ">=4.6.0"
transformers = ">=5.2.0"
matplotlib = ">=3.10.8"
pillow = ">=12.1.1"
scikit-learn = ">=1.8.0,<2"
numpy = ">=2.4.2,<3"

[pypi-dependencies]
moku = { path = ".", editable = true }
