#!/usr/bin/env python3
"""Moku corner annotation server.

Serves a browser-based annotation UI for correcting board_corner bboxes.

Usage:
    python tools/annotator/server.py \\
        --data-dir data/annotate \\
        --output  data/annotate/corrected.json \\
        --port    8765

Expected layout of ``data-dir``:
    data-dir/
        images/          # image files (JPEG or PNG)
        images.json      # generated by notebooks/05_Annotate.ipynb

``images.json`` schema::

    {
      "images": [
        {
          "id": 1,
          "filename": "foo.jpg",
          "width": 640,
          "height": 640,
          "source": "go_chess",
          "flagged": true,
          "flag_reason": "wrong_count (3 vs 4)"
        },
        ...
      ],
      "annotations": {
        "1": {"boxes": [{"id": 1, "x": 100, "y": 50, "w": 18, "h": 18, "category": 2}]},
        ...
      }
    }

Corrected annotations are saved to ``--output`` (default: ``data-dir/corrected.json``).
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path
from urllib.parse import unquote, urlparse

TOOL_DIR = Path(__file__).parent

# Shared server state (populated by main() before the server starts).
_STATE: dict = {}


class _Handler(BaseHTTPRequestHandler):
    """HTTP request handler for the annotation server."""

    def log_message(self, format, *args):  # noqa: A002
        pass  # Suppress per-request logging

    # ------------------------------------------------------------------
    # Routing
    # ------------------------------------------------------------------

    def do_GET(self):
        path = urlparse(self.path).path
        if path in ("/", "/index.html"):
            self._serve_file(TOOL_DIR / "index.html")
        elif path == "/annotator.js":
            self._serve_file(TOOL_DIR / "annotator.js")
        elif path == "/api/images":
            self._api_list_images()
        elif path.startswith("/api/image/"):
            self._api_serve_image(path[len("/api/image/") :])
        elif path.startswith("/api/annotations/"):
            self._api_get_annotations(path[len("/api/annotations/") :])
        else:
            self.send_error(404)

    def do_POST(self):
        path = urlparse(self.path).path
        if path.startswith("/api/annotations/"):
            self._api_save_annotations(path[len("/api/annotations/") :])
        else:
            self.send_error(404)

    # ------------------------------------------------------------------
    # API handlers
    # ------------------------------------------------------------------

    def _api_list_images(self):
        images = [dict(img) for img in _STATE["images_meta"]["images"]]
        for img in images:
            fname = img["filename"]
            img["annotated"] = fname in _STATE["corrections"]
            boxes = _STATE["corrections"].get(fname, {}).get("boxes", [])
            img["corner_count"] = sum(1 for b in boxes if b.get("category") == 2)
        self._json({"images": images})

    def _api_serve_image(self, filename: str):
        img_path = _STATE["data_dir"] / "images" / filename
        if not img_path.exists():
            self.send_error(404)
            return
        mime, _ = mimetypes.guess_type(filename)
        self._respond(img_path.read_bytes(), mime or "image/jpeg")

    def _api_get_annotations(self, raw_key: str):
        key = unquote(raw_key)
        ann = _STATE["corrections"].get(key) or _STATE["orig_annotations"].get(key, {"boxes": []})
        self._json(ann)

    def _api_save_annotations(self, raw_key: str):
        key = unquote(raw_key)
        length = int(self.headers.get("Content-Length", 0))
        data = json.loads(self.rfile.read(length))
        _STATE["corrections"][key] = data
        output_file: Path = _STATE["output_file"]
        output_file.write_text(json.dumps(_STATE["corrections"], indent=2))
        self._json({"status": "ok"})

    # ------------------------------------------------------------------
    # Response helpers
    # ------------------------------------------------------------------

    def _serve_file(self, path: Path):
        if not path.exists():
            self.send_error(404)
            return
        mime, _ = mimetypes.guess_type(str(path))
        self._respond(path.read_bytes(), mime or "application/octet-stream")

    def _json(self, data: dict, status: int = 200):
        self._respond(json.dumps(data).encode(), "application/json", status)

    def _respond(self, content: bytes, content_type: str, status: int = 200):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(content)))
        self.end_headers()
        self.wfile.write(content)


def main():
    parser = argparse.ArgumentParser(
        description="Moku corner annotation server",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--data-dir", required=True, type=Path, help="Directory containing images/ and images.json")
    parser.add_argument(
        "--output", type=Path, default=None, help="Output corrections JSON (default: data-dir/corrected.json)"
    )
    parser.add_argument("--port", type=int, default=8765, help="Server port (default: 8765)")
    args = parser.parse_args()

    data_dir = args.data_dir.resolve()
    output_file = (args.output or data_dir / "corrected.json").resolve()
    images_file = data_dir / "images.json"

    if not images_file.exists():
        print(
            f"ERROR: {images_file} not found.\nRun notebooks/05_Annotate.ipynb first to generate it.",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(images_file) as f:
        images_data = json.load(f)

    # Load existing corrections (if any) so progress is preserved across restarts.
    corrections: dict = {}
    if output_file.exists():
        with open(output_file) as f:
            corrections = {str(k): v for k, v in json.load(f).items()}

    _STATE.update(
        {
            "data_dir": data_dir,
            "output_file": output_file,
            "images_meta": {"images": images_data["images"]},
            "orig_annotations": {str(k): v for k, v in images_data.get("annotations", {}).items()},
            "corrections": corrections,
        }
    )

    server = HTTPServer(("localhost", args.port), _Handler)
    print(f"Moku Annotator  →  http://localhost:{args.port}")
    print(f"  data-dir  : {data_dir}")
    print(f"  output    : {output_file}")
    print("Press Ctrl+C to stop.\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("Stopped.")


if __name__ == "__main__":
    main()
